package com.aicodereview.model;

public enum CommentType {
    LOGIC_ERROR,
    SECURITY_VULNERABILITY,
    PERFORMANCE_ISSUE,
    STYLE_VIOLATION,
    BEST_PRACTICE,
    TEST_COVERAGE,
    DOCUMENTATION,
    REFACTORING_SUGGESTION,
    CODE_SMELL,
    ARCHITECTURE_CONCERN,
    DEPENDENCY_ISSUE,
    COMPATIBILITY_ISSUE
} 