server:
  port: 8080

spring:
  application:
    name: ai-code-review
  datasource:
    url: jdbc:h2:mem:aicodereviewdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=3600s

logging:
  level:
    com.aicodereview: DEBUG
    org.springframework: INFO

llm:
  provider: ${LLM_PROVIDER:ollama}  # Options: ollama, openai, anthropic, azure
  ollama:
    api:
      url: http://localhost:11434
      model: codellama
      temperature: 0.7
      max-tokens: 2000
      timeout: 30000

openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key}
    model: gpt-4
    temperature: 0.7
    max-tokens: 2000
    timeout: 30000

mcp:
  rules:
    path: classpath:mcp/rules/
  cache:
    enabled: true
    ttl: 3600 # 1 hour in seconds

github:
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET:your-webhook-secret}
    enabled: true
    path: /api/webhook/github
  app:
    id: ${GITHUB_APP_ID:your-app-id}
    private-key: ${GITHUB_PRIVATE_KEY:your-private-key}
  token: ${GITHUB_TOKEN:your-github-token} 